Fixed top features plot sorting
leekgroup/regionReport pull request #9
Opened 2018-02-13 04:41 UTC by bounlu

Previously the top n features were not correctly picked according to the sorted padj values. Also changed the x label legends to vertical to make the long labels readable without overlapping.

2018-02-13 15:40 UTC, lcolladotor commented
Hi @bounlu,

Thank you for the pull request. Can you add yourself as a `ctb` under the DESCRIPTION file? Also, please fix the missing parenthesis.

Thanks,
Leonardo

2018-03-21 20:38 UTC, lcolladotor requested changes
Fix parenthesis. Add yourself to contributors

2018-07-24 17:30 UTC, lcolladotor commented
Hi @@bounlu,

Do you want to fix your PR? If you don't have time let me know.

Best,
Leo

2018-07-24 18:12 UTC, bounlu commented
Hi,

I don't know how to fix it. Please go ahead as you wish.

Best.

2018-07-24 19:39 UTC, lcolladotor commented
Hi @bounlu,

Thanks for your PR. I implemented it in bioc-devel 3.8 (https://github.com/leekgroup/regionReport/commit/827ff5f2b9fd1b15169d1e94aad8761bd72336c8) and bioc-release 3.7 (https://github.com/leekgroup/regionReport/commit/dafbbdb01c8d1aa7d952d388cb42149835a0a096)

I didn't know either how to fix the conflicts in your PR with the rest of the GitHub history. In any case, your changes are there. Thanks again!

Best,
Leo

2018-07-24 19:39 UTC, closed without merging